version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: codecollab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:5000
      - VITE_WS_BASE=http://localhost:5000/ws 
    depends_on:
      - backend

volumes:
  pgdata: